services:
  postgres:
    image: postgres:16-alpine
    container_name: tiktok-postgres
    environment:
      POSTGRES_DB: tiktok_db
      POSTGRES_USER: tiktok
      POSTGRES_PASSWORD: tiktok123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tiktok -d tiktok_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
