FROM selenium/standalone-chrome:latest

# Instalar dependências adicionais se necessário
USER root
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Voltar para o usuário selenium
USER 1200

# Expor a porta do Chrome
EXPOSE 4444

# Comando para iniciar o Chrome
CMD ["selenium-standalone", "start", "--port", "4444", "--host", "0.0.0.0"]
